# add stages here 
stages:
  get_data:
    cmd: python src/stage_01.py
    deps:
    - src/stage_01.py
    - src/utils/common.py
    outs:
    - artifacts/raw_local_dir/data.csv

  # stage_two:
  #   cmd: python src/stage_02.py
  #   deps:
  #   - src/stage_02.py
  #   - output.txt
  #   outs:
  #   - output2.txt

  # stage_three:
  #   cmd: python src/stage_03.py
  #   deps:
  #   - src/stage_03.py
  #   - output.txt


